import { StyleSheet } from 'react-native';

// Preserve the existing patient dashboard palette.
export const C = { background: '#f3faff', primary: '#004c5b', teal: '#176577', secondary: '#00696e', aqua: '#84f4fb', pale: '#e6f6ff', icon: '#e0f0f9', text: '#0e1e23', muted: '#3f484b' };
const regular = 'ProfileInter400';
const medium = 'ProfileInter500';
const semibold = 'ProfileInter600';
const bold = 'ProfileInter700';
const shadow = '0 4px 18px rgba(0,76,91,0.04)';

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: C.background },
  headerSafe: { backgroundColor: '#fff', borderBottomWidth: 1, borderBottomColor: C.icon },
  header: { width: '100%', maxWidth: 1120, alignSelf: 'center', height: 72, paddingHorizontal: 20, flexDirection: 'row', alignItems: 'center', gap: 12 },
  grow: { flex: 1, minWidth: 0 },
  logo: { width: 40, height: 40, borderRadius: 12, backgroundColor: C.primary, alignItems: 'center', justifyContent: 'center' },
  eyebrow: { fontFamily: semibold, fontSize: 10, lineHeight: 14, letterSpacing: 1.2, color: C.secondary },
  headerTitle: { fontFamily: bold, fontSize: 17, lineHeight: 22, color: C.text },
  iconButton: { width: 44, height: 44, borderRadius: 14, borderWidth: 1, borderColor: C.icon, backgroundColor: '#fff', alignItems: 'center', justifyContent: 'center' },
  avatar: { width: 40, height: 40, borderRadius: 14, alignItems: 'center', justifyContent: 'center', backgroundColor: C.pale },
  content: { width: '100%', maxWidth: 1120, alignSelf: 'center', padding: 20, paddingBottom: 40, gap: 28 },
  intro: { gap: 8 },
  introTop: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12, flexWrap: 'wrap' },
  overline: { fontFamily: semibold, fontSize: 11, lineHeight: 16, letterSpacing: 1.5, color: C.secondary },
  greeting: { fontFamily: bold, fontSize: 28, lineHeight: 36, letterSpacing: -0.8, color: C.text },
  subtitle: { fontFamily: regular, color: C.muted, fontSize: 13, lineHeight: 20 },
  datePill: { flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: 12, paddingVertical: 8, borderRadius: 12, backgroundColor: C.pale },
  dateText: { fontFamily: medium, color: C.primary, fontSize: 11, lineHeight: 16 },
  search: { minHeight: 50, borderRadius: 16, paddingHorizontal: 16, flexDirection: 'row', alignItems: 'center', gap: 12, backgroundColor: '#fff', borderWidth: 1, borderColor: C.icon },
  searchText: { flex: 1, fontFamily: regular, fontSize: 13, lineHeight: 20, color: C.muted },
  stats: { flexDirection: 'row', gap: 10 },
  stat: { flex: 1, minWidth: 0, padding: 14, borderRadius: 16, backgroundColor: '#fff', borderWidth: 1, borderColor: C.icon, gap: 8, boxShadow: shadow },
  statIcon: { width: 32, height: 32, borderRadius: 10, alignItems: 'center', justifyContent: 'center', backgroundColor: C.pale },
  statValue: { fontFamily: bold, fontSize: 25, lineHeight: 32, letterSpacing: -0.6, color: C.primary },
  statLabel: { fontFamily: medium, fontSize: 11, lineHeight: 16, color: C.muted },
  status: { borderRadius: 14, padding: 16, flexDirection: 'row', alignItems: 'center', gap: 10, backgroundColor: C.pale },
  statusText: { flexShrink: 1, fontFamily: regular, fontSize: 13, lineHeight: 20, color: C.muted },
  error: { padding: 16, borderRadius: 16, backgroundColor: '#ffdad6', gap: 6 },
  errorTitle: { fontFamily: semibold, color: '#93000a', fontSize: 14, lineHeight: 20 },
  link: { fontFamily: semibold, color: C.secondary, fontSize: 12, lineHeight: 18 },
  textButton: { minHeight: 44, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 4 },
  section: { gap: 14 },
  sectionHeading: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
  sectionTitle: { fontFamily: bold, color: C.text, fontSize: 18, lineHeight: 26, letterSpacing: -0.3, flexShrink: 1 },
  sectionCaption: { fontFamily: regular, color: C.muted, fontSize: 12, lineHeight: 18 },
  booking: { borderRadius: 20, padding: 22, gap: 16, overflow: 'hidden' },
  bookingDecoration: { position: 'absolute', width: 210, height: 210, borderRadius: 105, borderWidth: 32, borderColor: 'rgba(255,255,255,0.06)', right: -75, bottom: -95 },
  bookingTop: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  bookingEyebrow: { flexShrink: 1, fontFamily: semibold, fontSize: 10, lineHeight: 16, letterSpacing: 1.4, color: C.aqua },
  bookingTitle: { fontFamily: bold, fontSize: 23, lineHeight: 30, letterSpacing: -0.5, color: '#fff' },
  bookingBody: { fontFamily: regular, color: 'rgba(255,255,255,0.85)', fontSize: 13, lineHeight: 20, maxWidth: 480 },
  bookingFooter: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 14, flexWrap: 'wrap' },
  bookingMeta: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  bookingMetaText: { fontFamily: medium, fontSize: 11, lineHeight: 16, color: C.aqua },
  bookButton: { minHeight: 44, paddingHorizontal: 16, borderRadius: 12, backgroundColor: '#fff', flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8 },
  bookButtonLabel: { fontFamily: semibold, color: C.primary, fontSize: 12, lineHeight: 18 },
  overview: { gap: 14 }, wideRow: { flexDirection: 'row' },
  careCard: { padding: 18, borderRadius: 18, backgroundColor: '#fff', borderWidth: 1, borderColor: C.icon, gap: 16, boxShadow: shadow },
  wideCard: { flex: 1 },
  cardTop: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', justifyContent: 'space-between', gap: 8 },
  cardType: { fontFamily: semibold, fontSize: 10, lineHeight: 16, color: C.secondary, letterSpacing: 1 },
  badge: { paddingHorizontal: 8, paddingVertical: 3, borderRadius: 8, backgroundColor: C.pale },
  badgeLabel: { fontFamily: medium, fontSize: 10, lineHeight: 14, color: C.secondary },
  careHeading: { fontFamily: bold, fontSize: 17, lineHeight: 24, color: C.text, letterSpacing: -0.2 },
  careNumber: { fontFamily: bold, fontSize: 34, lineHeight: 42, color: C.primary, letterSpacing: -1 },
  careDescription: { flexShrink: 1, fontFamily: regular, fontSize: 12, lineHeight: 18, color: C.muted },
  cardMeta: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  cardFooter: { borderTopWidth: 1, borderTopColor: C.icon, paddingTop: 12, marginTop: 'auto', minHeight: 44, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8 },
  actionScroll: { marginHorizontal: -20 }, actionContent: { paddingHorizontal: 20, gap: 10, paddingBottom: 4 },
  action: { width: 140, minHeight: 128, padding: 16, borderRadius: 16, borderWidth: 1, borderColor: C.icon, backgroundColor: '#fff', gap: 14 },
  actionIcon: { width: 38, height: 38, borderRadius: 12, backgroundColor: C.pale, alignItems: 'center', justifyContent: 'center' },
  actionLabel: { fontFamily: semibold, color: C.text, fontSize: 13, lineHeight: 18 },
  specialties: { flexDirection: 'column', gap: 10 },
  specialty: { width: '100%', minHeight: 60, flexDirection: 'row', alignItems: 'center', gap: 14, paddingHorizontal: 16, paddingVertical: 12, borderRadius: 16, backgroundColor: '#fff', borderWidth: 1, borderColor: C.icon, boxShadow: shadow },
  specialtyIcon: { width: 40, height: 40, borderRadius: 12, backgroundColor: C.pale, justifyContent: 'center', alignItems: 'center' },
  specialtyLabel: { flex: 1, fontFamily: semibold, fontSize: 14, lineHeight: 20, color: C.text },
  activityCard: { borderWidth: 1, borderColor: C.icon, backgroundColor: '#fff', borderRadius: 18, overflow: 'hidden' },
  activityRow: { padding: 16, flexDirection: 'row', alignItems: 'center', gap: 12 },
  activityTitle: { fontFamily: semibold, color: C.text, fontSize: 13, lineHeight: 18 },
  activityCaption: { fontFamily: regular, color: C.muted, fontSize: 11, lineHeight: 16, marginTop: 3 },
  divider: { height: 1, backgroundColor: C.icon, marginHorizontal: 16 },
  emptyActivity: { padding: 20, gap: 6 },
  events: { marginHorizontal: -20 }, eventContent: { paddingHorizontal: 20, gap: 16, paddingBottom: 4 },
  eventCard: { width: 280, borderRadius: 18, backgroundColor: '#fff', overflow: 'hidden', borderWidth: 1, borderColor: C.icon },
  eventImage: { width: '100%', height: 144 }, eventBody: { padding: 16, gap: 6 },
  eventBadge: { position: 'absolute', top: 12, left: 12, backgroundColor: '#fff', borderRadius: 8, paddingHorizontal: 8, paddingVertical: 4 },
  eventBadgeText: { fontFamily: semibold, fontSize: 10, lineHeight: 14, color: C.primary },
  eventTitle: { fontFamily: semibold, color: C.text, fontSize: 14, lineHeight: 20 },
  eventDescription: { fontFamily: regular, color: C.muted, fontSize: 12, lineHeight: 18 },
  eventSchedule: { flexShrink: 1, fontFamily: medium, color: C.secondary, fontSize: 11, lineHeight: 16 },
  modalOverlay: { flex: 1, justifyContent: 'flex-end', alignItems: 'center', backgroundColor: 'rgba(0,76,91,0.35)' },
  sheet: { width: '100%', maxWidth: 480, maxHeight: '85%', borderTopLeftRadius: 24, borderTopRightRadius: 24, padding: 24, backgroundColor: '#fff', gap: 16 },
  sheetBody: { fontFamily: regular, color: C.muted, fontSize: 14, lineHeight: 22 },
  sheetButton: { minHeight: 44, backgroundColor: C.primary, borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
  sheetButtonLabel: { fontFamily: semibold, color: '#fff', fontSize: 14, lineHeight: 20 },
  pressed: { opacity: 0.7 },
});
