import { StyleSheet } from 'react-native';

export const C = {
  background: '#f3faff', primary: '#004c5b', container: '#176577', secondary: '#00696e',
  aqua: '#84f4fb', pale: '#e6f6ff', icon: '#e0f0f9', high: '#daebf3', text: '#0e1e23',
  muted: '#3f484b', light: '#9de0f5', error: '#ba1a1a', white: '#ffffff',
};
const fontFamily = 'ProfileInter400';
const shadow = '0 4px 20px -2px rgba(19,34,40,0.06)';

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: C.background },
  headerSafe: { backgroundColor: C.background, zIndex: 10, boxShadow: '0 4px 20px -2px rgba(19,34,40,0.05)' },
  header: { height: 64, paddingHorizontal: 20, flexDirection: 'row', alignItems: 'center', gap: 8 },
  headerIcon: { width: 36, height: 36, borderRadius: 12, alignItems: 'center', justifyContent: 'center', backgroundColor: '#dcebef' },
  headerTitle: { fontFamily: 'ProfileInter600', fontSize: 18, fontWeight: 'normal', color: C.primary },
  headerAvatar: { minWidth: 44, minHeight: 44, alignItems: 'center', justifyContent: 'center' },
  content: { paddingBottom: 48 }, grow: { flex: 1, minWidth: 0 }, horizontal: { flexDirection: 'row', gap: 4, alignItems: 'center' },
  iconButton: { width: 44, height: 44, borderRadius: 22, alignItems: 'center', justifyContent: 'center' },
  lightButton: { width: 40, height: 40, borderRadius: 20, backgroundColor: 'rgba(255,255,255,0.15)' },
  hero: { backgroundColor: C.primary, paddingHorizontal: 20, paddingTop: 16, paddingBottom: 56, borderBottomLeftRadius: 32, borderBottomRightRadius: 32, overflow: 'hidden', boxShadow: '0 12px 30px -8px rgba(0,76,91,0.22)' },
  heroActions: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 16 },
  registeredPill: { flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: 12, paddingVertical: 4, borderRadius: 20, backgroundColor: 'rgba(255,255,255,0.15)' },
  registeredText: { fontFamily: 'ProfileInter500', color: C.white, fontSize: 11, letterSpacing: 0.22, fontWeight: 'normal' },
  aquaDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: C.aqua },
  identity: { flexDirection: 'row', alignItems: 'center', gap: 16 },
  avatarFrame: { width: 80, height: 80, padding: 4, borderRadius: 40, backgroundColor: 'rgba(255,255,255,0.3)' },
  avatar: { flex: 1, backgroundColor: C.icon, borderRadius: 40, alignItems: 'center', justifyContent: 'center' },
  avatarText: { fontFamily: 'ProfileInter700', color: C.primary, fontSize: 26, fontWeight: 'normal' },
  smallAvatar: { width: 32, height: 32, flex: 0, borderRadius: 16 }, smallAvatarText: { fontSize: 11 },
  patientName: { fontFamily: 'ProfileInter700', color: C.white, fontSize: 22, lineHeight: 28, fontWeight: 'normal', letterSpacing: -0.22 },
  patientMeta: { fontFamily, color: C.light, fontSize: 12, lineHeight: 16, marginTop: 2 },
  idPill: { flexDirection: 'row', alignItems: 'center', gap: 6, alignSelf: 'flex-start', paddingHorizontal: 10, paddingVertical: 2, marginTop: 8, borderRadius: 20, backgroundColor: C.container },
  idText: { fontFamily, color: C.light, fontSize: 11, lineHeight: 14 },
  metricWrap: { marginTop: -32, marginHorizontal: 20 },
  metrics: { flexDirection: 'row', borderRadius: 12, padding: 16, backgroundColor: C.white, boxShadow: '0 8px 24px -4px rgba(19,34,40,0.08)' },
  metric: { flex: 1, alignItems: 'center' }, metricValueRow: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  metricValue: { fontFamily: 'ProfileInter800', fontSize: 28, lineHeight: 34, fontWeight: 'normal', color: C.primary, letterSpacing: -0.56 },
  metricLabel: { fontFamily, fontSize: 11, lineHeight: 14, marginTop: 2, color: C.muted },
  activeDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: C.secondary },
  tabsWrap: { marginHorizontal: 20, marginTop: 24, borderRadius: 30, backgroundColor: C.high, overflow: 'hidden' },
  tabs: { flexGrow: 1, padding: 4 }, tab: { flexGrow: 1, paddingHorizontal: 12, paddingVertical: 8, borderRadius: 24, justifyContent: 'center' },
  selectedTab: { backgroundColor: C.primary }, tabLabel: { fontFamily: 'ProfileInter600', fontSize: 12, lineHeight: 16, fontWeight: 'normal', color: C.muted }, selectedLabel: { color: C.white },
  queueWrap: { marginHorizontal: 20, marginTop: 16 },
  queueBanner: { padding: 16, borderRadius: 12, flexDirection: 'row', gap: 8, alignItems: 'center', overflow: 'hidden', boxShadow: '0 6px 20px -3px rgba(23,101,119,0.25)' },
  queueIcon: { width: 40, height: 40, borderRadius: 20, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(255,255,255,0.2)' },
  queueTitle: { fontFamily: 'ProfileInter600', fontSize: 18, lineHeight: 22, fontWeight: 'normal', color: C.white },
  queueCaption: { fontFamily, fontSize: 12, lineHeight: 16, color: C.pale, marginTop: 2 },
  activeBadge: { borderRadius: 20, paddingHorizontal: 8, paddingVertical: 2, backgroundColor: C.aqua }, activeText: { fontFamily, fontSize: 11, color: '#007075' },
  queueArrow: { width: 36, height: 36, borderRadius: 18, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(255,255,255,0.2)' },
  queueRing: { position: 'absolute', right: -4, bottom: -4, width: 80, height: 80, borderRadius: 40, borderWidth: 12, borderColor: 'rgba(255,255,255,0.15)' },
  section: { marginHorizontal: 20, marginTop: 24, gap: 16 }, sectionHeading: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8 },
  sectionTitle: { fontFamily: 'ProfileInter600', fontSize: 18, lineHeight: 24, fontWeight: 'normal', color: C.text, letterSpacing: -0.09 },
  caption: { fontFamily, fontSize: 12, lineHeight: 16, color: C.muted },
  link: { fontFamily: 'ProfileInter600', color: C.primary, fontSize: 12, lineHeight: 16, fontWeight: 'normal' },
  exportButton: { minHeight: 44, flexDirection: 'row', alignItems: 'center', gap: 4 },
  filters: { gap: 8, paddingTop: 4 }, filter: { paddingHorizontal: 14, paddingVertical: 6, borderRadius: 24, justifyContent: 'center', backgroundColor: C.icon },
  filterLabel: { fontFamily: 'ProfileInter500', color: C.muted, fontSize: 11, lineHeight: 14, fontWeight: 'normal' },
  visitCard: { padding: 16, borderRadius: 12, backgroundColor: C.white, boxShadow: shadow, gap: 8 },
  visitHeading: { flexDirection: 'row', alignItems: 'flex-start', gap: 8 },
  squareIcon: { width: 40, height: 40, borderRadius: 12, alignItems: 'center', justifyContent: 'center', backgroundColor: C.icon },
  rowTitle: { fontFamily: 'ProfileInter600', color: C.text, fontSize: 14, lineHeight: 18, fontWeight: 'normal', letterSpacing: 0.14 },
  statusPill: { flexDirection: 'row', alignItems: 'center', gap: 4, paddingHorizontal: 10, paddingVertical: 4, borderRadius: 20, backgroundColor: C.icon, maxWidth: '35%' },
  statusDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: C.secondary }, statusLabel: { fontFamily, fontSize: 11, lineHeight: 14, color: C.secondary, textTransform: 'capitalize', flexShrink: 1 },
  visitDetails: { borderRadius: 8, backgroundColor: C.pale, padding: 8, gap: 6 },
  visitDateRow: { flexDirection: 'row', alignItems: 'center', gap: 4, flexWrap: 'wrap' },
  visitDate: { fontFamily, fontSize: 11, lineHeight: 14, color: C.muted, flex: 1 },
  tokenPill: { backgroundColor: '#afecff', borderRadius: 20, paddingHorizontal: 8, paddingVertical: 2 }, tokenLabel: { fontFamily: 'ProfileInter600', color: C.primary, fontSize: 12, lineHeight: 16, fontWeight: 'normal' },
  reasonLabel: { fontFamily, fontSize: 11, lineHeight: 14, letterSpacing: 0.8, color: C.muted },
  reason: { fontFamily, fontSize: 12, lineHeight: 16, color: C.text },
  visitActions: { flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap', gap: 8, paddingTop: 4 },
  actionChip: { flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: 12, paddingVertical: 6, borderRadius: 24, backgroundColor: C.icon },
  actionLabel: { fontFamily: 'ProfileInter500', fontSize: 11, lineHeight: 14, fontWeight: 'normal', color: C.primary },
  downloadButton: { width: 36, height: 36, borderRadius: 18, alignItems: 'center', justifyContent: 'center', backgroundColor: C.icon },
  moreButton: { minHeight: 44, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8 },
  vault: { flexDirection: 'row', alignItems: 'center', gap: 8, padding: 16, borderRadius: 12, backgroundColor: C.pale },
  vaultButton: { minHeight: 44, paddingHorizontal: 14, borderRadius: 24, backgroundColor: C.white, justifyContent: 'center' },
  roundIcon: { width: 40, height: 40, borderRadius: 20, backgroundColor: C.icon, alignItems: 'center', justifyContent: 'center' },
  accountCard: { borderRadius: 12, backgroundColor: C.white, overflow: 'hidden', boxShadow: shadow },
  accountRow: { padding: 16, gap: 16, flexDirection: 'row', alignItems: 'center', backgroundColor: C.white },
  logoutWrap: { marginHorizontal: 20, marginTop: 24, marginBottom: 40 },
  logoutButton: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, paddingVertical: 14, borderRadius: 30, backgroundColor: C.icon },
  logoutLabel: { fontFamily: 'ProfileInter600', color: C.error, fontSize: 14, lineHeight: 18, fontWeight: 'normal' },
  infoCard: { paddingHorizontal: 16, backgroundColor: C.white, borderRadius: 12, boxShadow: shadow },
  infoRow: { paddingVertical: 12, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: C.icon, gap: 4 },
  infoValue: { fontFamily, color: C.text, fontSize: 14, lineHeight: 20 },
  documentCard: { flexDirection: 'row', gap: 12, alignItems: 'center', padding: 16, borderRadius: 12, backgroundColor: C.white, boxShadow: shadow },
  empty: { backgroundColor: C.white, padding: 20, borderRadius: 12, gap: 8 },
  error: { fontFamily, color: C.error, fontSize: 12, lineHeight: 18 },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(36,51,57,0.6)', justifyContent: 'flex-end', alignItems: 'center' },
  sheet: { width: '100%', maxWidth: 448, maxHeight: '90%', borderTopLeftRadius: 32, borderTopRightRadius: 32, padding: 24, backgroundColor: C.white, gap: 16 },
  sheetHandle: { alignSelf: 'center', width: 48, height: 6, borderRadius: 3, backgroundColor: '#d5e5ed' },
  sheetBody: { fontFamily, color: C.muted, fontSize: 14, lineHeight: 20 },
  qrFrame: { padding: 24, alignSelf: 'center', borderRadius: 16, backgroundColor: C.white, boxShadow: '0 8px 30px rgba(0,0,0,0.08)' },
  passRecap: { padding: 12, borderRadius: 12, backgroundColor: C.pale, alignItems: 'center', gap: 4 },
  sheetButton: { paddingVertical: 14, borderRadius: 30, backgroundColor: C.primary, alignItems: 'center' },
  sheetButtonLabel: { fontFamily: 'ProfileInter600', color: C.white, fontWeight: 'normal', fontSize: 14, lineHeight: 18 },
  pressed: { opacity: 0.7 }, disabled: { opacity: 0.5 },
});
