import { StyleSheet } from 'react-native';

export const C = {
  background: '#f3faff', primary: '#004c5b', container: '#176577', secondary: '#00696e',
  aqua: '#84f4fb', pale: '#e6f6ff', surface: '#ffffff', icon: '#e0f0f9', high: '#daebf3',
  text: '#0e1e23', muted: '#3f484b', light: '#afecff', error: '#ba1a1a',
};
const regular = 'ProfileInter400';
const medium = 'ProfileInter500';
const semibold = 'ProfileInter600';
const bold = 'ProfileInter700';
const heavy = 'ProfileInter800';
const shadow = '0 4px 20px -2px rgba(19,34,40,0.06), 0 1px 3px rgba(19,34,40,0.04)';

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: C.background },
  headerSafe: { zIndex: 10, backgroundColor: C.background, boxShadow: '0 1px 8px rgba(0,0,0,0.04)' },
  header: { height: 64, paddingHorizontal: 20, flexDirection: 'row', alignItems: 'center', gap: 8 },
  logo: { width: 36, height: 36, borderRadius: 18, backgroundColor: C.container, alignItems: 'center', justifyContent: 'center' },
  grow: { flex: 1, minWidth: 0 },
  eyebrow: { fontFamily: medium, color: C.secondary, fontSize: 11, lineHeight: 14, letterSpacing: 1.1 },
  headerTitle: { fontFamily: semibold, color: C.text, fontSize: 18, lineHeight: 24 },
  iconButton: { width: 44, height: 44, borderRadius: 22, alignItems: 'center', justifyContent: 'center' },
  profileButton: { width: 32, height: 32, borderRadius: 16, backgroundColor: C.primary, alignItems: 'center', justifyContent: 'center' },
  content: { paddingBottom: 40 },
  hero: { paddingHorizontal: 20, paddingTop: 12, paddingBottom: 48, backgroundColor: C.primary, overflow: 'hidden' },
  heroWaveRight: { position: 'absolute', right: -24, bottom: -32, width: 288, height: 176 },
  heroWaveLeft: { position: 'absolute', left: -48, top: -40, width: 240, height: 160 },
  heroRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12, marginBottom: 16 },
  lightButton: { width: 40, height: 40, borderRadius: 20, backgroundColor: 'rgba(255,255,255,0.15)', alignItems: 'center', justifyContent: 'center' },
  heroTitle: { fontFamily: bold, fontSize: 18, lineHeight: 24, color: C.surface, textAlign: 'center', letterSpacing: -0.09 },
  heroSubtitle: { fontFamily: medium, fontSize: 11, lineHeight: 14, color: '#8dd0e5', textAlign: 'center' },
  stack: { paddingHorizontal: 20, marginTop: -32, gap: 16 },
  card: { borderRadius: 12, backgroundColor: C.surface, boxShadow: shadow, overflow: 'hidden' },
  clinicRow: { padding: 16, paddingBottom: 8, flexDirection: 'row', alignItems: 'center', gap: 8 },
  clinicIcon: { width: 40, height: 40, borderRadius: 20, backgroundColor: '#cefafd', alignItems: 'center', justifyContent: 'center' },
  title: { fontFamily: bold, color: C.text, fontSize: 18, lineHeight: 24 },
  caption: { fontFamily: regular, color: C.muted, fontSize: 12, lineHeight: 16 },
  small: { fontFamily: medium, color: C.muted, fontSize: 11, lineHeight: 14 },
  roomPill: { flexDirection: 'row', alignItems: 'center', gap: 4, paddingHorizontal: 10, paddingVertical: 4, borderRadius: 20, backgroundColor: C.high, maxWidth: '33%' },
  roomDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: C.secondary },
  roomText: { fontFamily: semibold, color: C.primary, fontSize: 11, lineHeight: 14, flexShrink: 1 },
  numberPanel: { marginHorizontal: 16, marginVertical: 4, padding: 16, borderRadius: 8, backgroundColor: C.pale, overflow: 'hidden', gap: 2 },
  numberRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8, flexWrap: 'wrap' },
  queueNumber: { fontFamily: heavy, color: C.text, fontSize: 28, lineHeight: 34, letterSpacing: -0.56 },
  aheadPill: { paddingHorizontal: 8, paddingVertical: 2, borderRadius: 20, backgroundColor: '#c1f7fc' },
  aheadText: { fontFamily: semibold, color: C.secondary, fontSize: 12, lineHeight: 16 },
  numberWave: { position: 'absolute', right: 0, bottom: 0, width: 144, height: 64 },
  estimate: { marginHorizontal: 16, marginBottom: 16, paddingHorizontal: 16, paddingVertical: 12, borderRadius: 8, backgroundColor: C.container, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 8 },
  inline: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  estimateLabel: { fontFamily: semibold, color: C.surface, fontSize: 14, lineHeight: 18 },
  estimateValue: { fontFamily: bold, color: C.light, fontSize: 18, lineHeight: 24, flexShrink: 1, textAlign: 'right' },
  guidance: { flexDirection: 'row', alignItems: 'flex-start', gap: 8, paddingHorizontal: 16, paddingVertical: 8, borderRadius: 12, backgroundColor: C.icon },
  guidanceBody: { fontFamily: regular, color: C.muted, fontSize: 12, lineHeight: 19.5, flex: 1 },
  qrCard: { padding: 24, borderRadius: 12, backgroundColor: C.surface, alignItems: 'center', boxShadow: shadow },
  qrFrame: { padding: 16, backgroundColor: C.surface, borderRadius: 8, boxShadow: '0 1px 3px rgba(19,34,40,0.04)' },
  scanDot: { position: 'absolute', top: -6, right: -6, width: 16, height: 16, borderRadius: 8, backgroundColor: C.secondary, borderWidth: 4, borderColor: '#50999d' },
  timer: { flexDirection: 'row', alignItems: 'center', gap: 6, marginTop: 8 },
  timerStrong: { fontFamily: bold, color: C.text },
  metadata: { width: '100%', marginTop: 24, padding: 8, borderRadius: 8, backgroundColor: '#eef9ff', flexDirection: 'row', gap: 4 },
  metaItem: { flex: 1, alignItems: 'center', minWidth: 0, gap: 2 },
  metaLabel: { fontFamily: medium, fontSize: 11, lineHeight: 14, color: C.muted, textAlign: 'center' },
  metaValue: { fontFamily: bold, fontSize: 14, lineHeight: 18, color: C.text, textAlign: 'center', width: '100%' },
  metaNumber: { fontFamily: heavy, fontSize: 18, lineHeight: 24, color: C.primary },
  pharmacy: { padding: 16, borderRadius: 12, backgroundColor: C.surface, boxShadow: shadow, flexDirection: 'row', alignItems: 'center', gap: 16 },
  specialist: { padding: 16, borderRadius: 12, backgroundColor: C.pale, flexDirection: 'row', alignItems: 'center', gap: 8 },
  doctorAvatar: { width: 48, height: 48, borderRadius: 24, backgroundColor: C.icon, alignItems: 'center', justifyContent: 'center' },
  specialistEyebrow: { fontFamily: semibold, fontSize: 11, lineHeight: 14, color: C.secondary, letterSpacing: 1.1 },
  contactButton: { width: 36, height: 36, borderRadius: 18, backgroundColor: C.surface, alignItems: 'center', justifyContent: 'center' },
  actions: { gap: 8, paddingTop: 4, paddingBottom: 24 },
  homeButton: { height: 52, borderRadius: 30, backgroundColor: C.primary, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, boxShadow: '0 4px 6px rgba(0,0,0,0.1)' },
  homeLabel: { fontFamily: semibold, color: C.surface, fontSize: 18, lineHeight: 24 },
  secondaryActions: { flexDirection: 'row', gap: 8 },
  walletButton: { flex: 1, minHeight: 44, borderRadius: 24, backgroundColor: C.icon, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6 },
  actionLabel: { fontFamily: semibold, color: C.text, fontSize: 14, lineHeight: 18 },
  shareButton: { width: 44, height: 44, borderRadius: 22, backgroundColor: C.icon, alignItems: 'center', justifyContent: 'center' },
  shareButtonRow: { height: 44, borderRadius: 22, backgroundColor: C.icon, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8 },
  stateCard: { padding: 20, borderRadius: 12, backgroundColor: C.surface, gap: 12, boxShadow: shadow },
  doctorSelect: { minHeight: 48, paddingHorizontal: 14, borderRadius: 10, borderWidth: 1, borderColor: '#bfc8cc', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8 },
  doctorSelectText: { fontFamily: semibold, color: C.text, fontSize: 14, flex: 1 },
  doctorMenu: { width: '92%', maxWidth: 520, padding: 20, borderRadius: 16, backgroundColor: C.surface, gap: 12, alignSelf: 'center', marginTop: 'auto', marginBottom: 'auto', boxShadow: shadow },
  doctorOption: { minHeight: 56, paddingHorizontal: 12, paddingVertical: 8, borderRadius: 10, backgroundColor: C.pale, flexDirection: 'row', alignItems: 'center', gap: 8 },
  error: { fontFamily: regular, color: C.error, fontSize: 12, lineHeight: 18 },
  modalOverlay: { flex: 1, justifyContent: 'flex-end', alignItems: 'center', backgroundColor: 'rgba(36,51,57,0.6)' },
  sheet: { width: '100%', maxWidth: 448, maxHeight: '90%', padding: 24, borderTopLeftRadius: 24, borderTopRightRadius: 24, backgroundColor: C.surface, gap: 16 },
  sheetHandle: { width: 48, height: 5, borderRadius: 3, alignSelf: 'center', backgroundColor: C.high },
  sheetBody: { fontFamily: regular, fontSize: 14, lineHeight: 20, color: C.muted },
  menuButton: { minHeight: 44, paddingHorizontal: 16, borderRadius: 24, backgroundColor: C.icon, justifyContent: 'center', alignItems: 'center' },
  pressed: { opacity: 0.7 }, disabled: { opacity: 0.5 },
});
